/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as EvidencesRouteImport } from './routes/evidences'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidencesRoute = EvidencesRouteImport.update({
  id: '/evidences',
  path: '/evidences',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evidences': typeof EvidencesRoute
  '/extensions': typeof ExtensionsRoute
  '/history': typeof HistoryRoute
  '/locations': typeof LocationsRoute
  '/risks': typeof RisksRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evidences': typeof EvidencesRoute
  '/extensions': typeof ExtensionsRoute
  '/history': typeof HistoryRoute
  '/locations': typeof LocationsRoute
  '/risks': typeof RisksRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evidences': typeof EvidencesRoute
  '/extensions': typeof ExtensionsRoute
  '/history': typeof HistoryRoute
  '/locations': typeof LocationsRoute
  '/risks': typeof RisksRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/evidences'
    | '/extensions'
    | '/history'
    | '/locations'
    | '/risks'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/evidences'
    | '/extensions'
    | '/history'
    | '/locations'
    | '/risks'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/evidences'
    | '/extensions'
    | '/history'
    | '/locations'
    | '/risks'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EvidencesRoute: typeof EvidencesRoute
  ExtensionsRoute: typeof ExtensionsRoute
  HistoryRoute: typeof HistoryRoute
  LocationsRoute: typeof LocationsRoute
  RisksRoute: typeof RisksRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidences': {
      id: '/evidences'
      path: '/evidences'
      fullPath: '/evidences'
      preLoaderRoute: typeof EvidencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EvidencesRoute: EvidencesRoute,
  ExtensionsRoute: ExtensionsRoute,
  HistoryRoute: HistoryRoute,
  LocationsRoute: LocationsRoute,
  RisksRoute: RisksRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
